name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log version
        run: npm -v

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            packages/*/package-lock.json

      - name: Bootstrap
        run: npm run bootstrap

      - name: Run test
        run: npm run test
